Run tests (Cog)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,27 +22,52 @@ jobs:
         uses: replicate/setup-cog@v2
         with:
           token: '${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}'
-      - name: Run tests (Cog) with media integration
+      - name: Run tests (Cog) with video integration
+        run: |
+          media_path="@thirdparty/20250401-0707-12.7226723.mp4"
+          cog predict -i test_mode=True -i "media_path=$media_path" | \
+                  tee \
+                          >(jq -r '.debug_media | split(",")[1]' | base64 -d > debug_output_video.mp4) \
+                          >(jq -r '.mediapipe' > mediapipe_video.json) \
+                          >(jq -r '.fullbody' > fullbody_video.json) \
+                          >(jq -r '.hand_landmarks' > hand_landmarks_video.json) \
+                          >(jq -r '.blendshapes' > blendshapes_video.json) \
+                  >/dev/null
+      - name: Run tests (Cog) with image integration
         run: |
           media_path="@thirdparty/image.jpg"
           cog predict -i "media_path=$media_path" | \
                   tee \
-                          >(jq -r '.debug_media | split(",")[1]' | base64 -d > debug_output.png) \
-                          >(jq -r '.mediapipe' > mediapipe.json) \
-                          >(jq -r '.fullbody' > fullbody.json) \
-                          >(jq -r '.hand_landmarks' > hand_landmarks.json) \
-                          >(jq -r '.blendshapes' > blendshapes.json) \
+                          >(jq -r '.debug_media | split(",")[1]' | base64 -d > debug_output_image.png) \
+                          >(jq -r '.mediapipe' > mediapipe_image.json) \
+                          >(jq -r '.fullbody' > fullbody_image.json) \
+                          >(jq -r '.hand_landmarks' > hand_landmarks_image.json) \
+                          >(jq -r '.blendshapes' > blendshapes_image.json) \
                   >/dev/null
       - name: Upload test artifacts
         uses: actions/upload-artifact@v4
         with:
           name: test-artifacts
           path: |
-            debug_output.png
-            mediapipe.json
-            fullbody.json
-            hand_landmarks.json
-            blendshapes.json
+            debug_output_video.mp4
+            mediapipe_video.json
+            fullbody_video.json
+            hand_landmarks_video.json
+            blendshapes_video.json
+            debug_output_image.png
+            mediapipe_image.json
+            fullbody_image.json
+            hand_landmarks_image.json
+            blendshapes_image.json
+      - name: Check artifact sizes
+        run: |
+          for file in debug_output_video.mp4 mediapipe_video.json fullbody_video.json hand_landmarks_video.json blendshapes_video.json \
+                      debug_output_image.png mediapipe_image.json fullbody_image.json hand_landmarks_image.json blendshapes_image.json; do
+            if [ ! -s "$file" ]; then
+              echo "Error: $file is empty or does not exist."
+              exit 1
+            fi
+          done
       - name: Push to Replicate
         if: github.ref == 'refs/heads/main'
         run: >-
